branch-defaults:
  default:
    environment: Senses-env
  master:
    environment: Senses-env
environment-defaults:
  Senses-env:
    branch: master
    repository: senses
global:
  application_name: Senses
  default_ec2_keyname: null
  default_platform: PHP 7.1
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli3
  sc: git
  workspace_type: Application
